DarkPlasma_StateAliasBySide:
  name: DarkPlasma_StateAliasBySide
  year: 2022
  license: MIT
  histories:
    - date: 2023/05/07
      version: 1.0.1
      description: 'typescript移行'
    - description: 'エイリアス元ステートの無効フラグを貫通する不具合を修正'
    - date: 2022/03/11
      version: 1.0.0
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: '敵味方に応じてステートを変更する'
  parameters: []
  commands: []
  structures:
  dependencies:
    base: []
    orderAfter: []
    orderBefore: []
  help:
    ja: |
      敵・味方に応じて別のステートを付与することができます。

      <stateAliasEnemy:X>
      ステートのメモ欄にこう記述した場合、
      敵にそのステートを付与する場合、
      代わりにステートID:Xのステートが付与されます。
      ステート有効度はXではなく元のステートのものが使用されます。
      ステート無効フラグは両方のステートのものが使用されます。

      <stateAliasActor:X>
      ステートのメモ欄にこう記述した場合、
      味方にそのステートを付与する場合、
      代わりにステートID:Xのステートが付与されます。
      ステート有効度はXではなく元のステートのものが使用されます。
      ステート無効フラグは両方のステートのものが使用されます。

      例:
      <stateAliasEnemy:14>
      ステートID4を敵に付与する場合、
      ステートID4ではなく14が付与されます。
      味方用の毒と敵用の毒を分けたい場合に有効です。

      この場合、ステート有効度はID4のものが使用されます。
      ステート無効フラグはID4, ID14どちらかがついていれば無効となります。
