DarkPlasma_NoStateBuffMap:
  name: DarkPlasma_NoStateBuffMap
  year: 2022
  license: MIT
  histories:
    - date: 2022/08/06
      version: 1.0.0
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: '戦闘不能以外のステート・バフにかからないマップ'
  parameters: []
  commands: []
  structures:
  dependencies:
    base: []
    orderAfter: []
    orderBefore: []
  help:
    ja: |
      メモ欄に <noStateBuff> と書かれたマップでは
      戦闘不能以外のステート・バフにかかりません。

      すでにステートやバフがかかった状態でそのマップに侵入した場合、
      ステートやバフが解除されます。
