DarkPlasma_FilterEquip_RecentlyGained:
  name: DarkPlasma_FilterEquip_RecentlyGained
  year: 2021
  license: MIT
  histories:
    - date: 2024/03/17
      version: 1.0.2
      description: 'TypeScript移行'
    - date: 2021/09/11
      version: 1.0.1
      description: 'クラスを上書きしないように変更'
    - date: 2021/09/05
      version: 1.0.0
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: '最近入手した装備を絞り込む'
  parameters:
    - param: threshold
      text:
        ja: 装備入手記録数
      desc:
        ja: この件数だけ装備の入手履歴を記録し、この履歴に含まれる装備を最近入手した装備として扱います
      type: number
      default: 5
      min: 1
    - param: traitName
      text:
        ja: 特徴名
      desc:
        ja: 絞り込み時に表示する特徴の名前を指定します
      type: string
      default: 最近入手した装備
  commands: []
  structures:
  dependencies:
    base:
      - name: DarkPlasma_FilterEquip
        version: 0.0.5
    orderAfter: []
    orderBefore: []
  help:
    ja: |
      DarkPlasma_FilterEquipによる装備絞り込みに「最近入手した装備」を追加します。
