DarkPlasma_SealItem:
  name: DarkPlasma_SealItem
  year: 2021
  license: MIT
  histories:
    - date: 2023/05/27
      version: 2.0.1
      description: '全アイテム禁止マップかどうか取得するインターフェース追加'
    - version: 2.0.0
      description: 'TypeScript移行'
    - description: '特徴の制御をAllocateUniqueTraitIdに任せる'
    - description: 'マップのメモ欄に対応'
    - date: 2021/07/05
      version: 1.0.2
      description: 'MZ 1.3.2に対応'
    - date: 2021/06/22
      version: 1.0.1
      description: 'サブフォルダからの読み込みに対応'
    - date: 2021/03/13
      version: 1.0.0
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: 'アイテムを封印する特徴'
  parameters: []
  commands: []
  structures:
  dependencies:
    base:
      - name: DarkPlasma_AllocateUniqueTraitId
        version: 1.0.1
    orderAfter:
      - name: DarkPlasma_AllocateUniqueTraitId
    orderBefore: []
  help:
    ja: |
      メモ欄に特定の書式で記述することにより、
      特定のアイテムが使用不能になる特徴を追加します。
      <sealAllItem>
        全てのアイテムが使用できなくなります。
      <sealItems:1,2>
        アイテムID1及び2のアイテムが使用できなくなります。
      <sealHealItem>
        HPまたはMP回復アイテムが使用できなくなります。
      <sealResurrectionItem>
        戦闘不能解除の効果を持つアイテムが使用できなくなります。

      同様のタグをマップのメモ欄に記述することにより、
      対象マップ内では特定のアイテムが使用不能になります。
