DarkPlasma_MultiElementAction:
  name: DarkPlasma_MultiElementAction
  year: 2023
  license: MIT
  histories:
    - date: 2023/03/29
      version: 1.0.0
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: '複数の属性を持つスキル・アイテム'
  parameters: []
  commands: []
  structures:
  dependencies:
    base: []
    orderAfter: []
    orderBefore: []
  help:
    ja: |
      スキルやアイテムに属性を追加します。

      属性を追加したいスキルやアイテムのメモ欄に
      <additionalElements:(属性名)>
      と記述してください。
      属性名はタイプで指定されている属性の名前です。

      例えば、物理属性のスキルに火属性を追加したい場合は
      <additionalElements:火>
      と記述します。

      複数の属性を追加する場合は、カンマで区切って追加します。
      <additionalElements:火,氷,雷>

      システムのタイプに存在しない名前を設定した場合、
      通常攻撃属性が追加されます。

      実際のダメージ計算に利用される属性は、
      RPGツクールMZのデフォルトでは最も有効な属性のみになります。
      本プラグインで追加した属性全てをダメージ計算に利用したい場合、
      DarkPlasma_MultiElementRate の利用を検討してください。
