DarkPlasma_SystemTypeIcon:
  name: DarkPlasma_SystemTypeIcon
  year: 2023
  license: MIT
  histories:
    - date: 2023/03/18
      version: 1.0.0
      description: '公開'

  locates:
    - ja
    - en
  plugindesc:
    ja: 'システムのタイプや弱体にアイコンを設定する'
    en: 'Set system type and debuff icons.'
  parameters:
    - param: elementIcons
      text:
        ja: 属性アイコン
        en: Element Icons
      desc:
        ja: 属性アイコンを設定します（順序はデータベースのタイプ設定に対応します）
        en: Element Icons for weak and resist.(The order is corresponding to elements settings in database.)
      type: icon[]
      default:
        - 0
        - 76
        - 64
        - 65
        - 66
        - 67
        - 68
        - 69
        - 70
        - 71
    - param: debuffStatusIcons
      text:
        ja: ステータス弱体アイコン
        en: Debuff Status Icons
      parent: debuffStatus
      type: DebuffStatusIcons
      default:
        mhp:
          small: 48
          large: 56
        mmp:
          small: 49
          large: 57
        atk:
          small: 50
          large: 58
        def:
          small: 51
          large: 59
        mat:
          small: 52
          large: 60
        mdf:
          small: 53
          large: 61
        agi:
          small: 54
          large: 62
        luk:
          small: 55
          large: 63
  commands: []
  structures:
    DebuffStatusIcons:
      - param: mhp
        text:
          ja: 最大HP弱体アイコン
          en: Debuff max hp icons
        type: DebuffStatusIcon
        default:
          small: 48
          large: 56
      - param: mmp
        text:
          ja: 最大MP弱体アイコン
          en: Debuff max mp icons
        type: DebuffStatusIcon
        default:
          small: 49
          large: 57
      - param: atk
        text:
          ja: 攻撃力弱体アイコン
          en: Debuff attack icons
        type: DebuffStatusIcon
        default:
          small: 50
          large: 58
      - param: def
        text:
          ja: 防御力弱体アイコン
          en: Debuff defense icons
        type: DebuffStatusIcon
        default:
          small: 51
          large: 59
      - param: mat
        text:
          ja: 魔法力弱体アイコン
          en: Debuff magical attack icons
        type: DebuffStatusIcon
        default:
          small: 52
          large: 60
      - param: mdf
        text:
          ja: 魔法防御弱体アイコン
          en: Debuff magical defense icons
        type: DebuffStatusIcon
        default:
          small: 53
          large: 61
      - param: agi
        text:
          ja: 敏捷性弱体アイコン
          en: Debuff agility icons
        type: DebuffStatusIcon
        default:
          small: 54
          large: 62
      - param: luk
        text:
          ja: 運弱体アイコン
          en: Debuff luck icons
        type: DebuffStatusIcon
        default:
          small: 55
          large: 63
    DebuffStatusIcon:
      - param: small
        text:
          ja: 弱体アイコン（小）
          en: Debuff status icon Lv1.
        type: number
      - param: large
        text:
          ja: 弱体アイコン（大）
          en: Debuff status icon Lv2.
        type: number
  dependencies:
    base: []
    orderAfter: []
    orderBefore: []
  help:
    ja: |
      システムのタイプや弱体にアイコンを設定します。
      本プラグインは、他プラグインでタイプや弱体に関するアイコンを扱う際に
      その補助とするための設定プラグインです。
      単体では機能しません。
    en: |
      Set icons for system types and debuffs.
