DarkPlasma_BattleGuide:
  name: DarkPlasma_BattleGuide
  year: 2022
  license: MIT
  histories:
    - date: 2022/04/24
      version: 1.0.0
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: '戦闘の手引書表示'
  parameters:
    - param: guides
      text:
        ja: 手引書
      type: Guide[]
    - param: listWidth
      text:
        ja: 目次横幅
      desc:
        ja: 手引書の目次ウィンドウの横幅を設定します。
      type: number
      default: 240
    - param: showPageNumber
      text:
        ja: ページ番号表示
      desc:
        ja: ページ番号の表示戦略を設定します。
      type: select
      default: 0
      options:
        - name: 'default(2ページ以上の場合表示)'
          value: 0
        - name: 'always(常に表示)'
          value: 1
        - name: 'no(表示なし)'
          value: 2
    - param: key
      text:
        ja: 手引書を開くキー
      type: select
      default: pageup
      options:
        - name: pageup
        - name: pagedown
        - name: shift
        - name: control
        - name: tab
    - param: addPartyCommand
      text:
        ja: パーティコマンドに追加する
      type: boolean
      default: true
    - param: partyCommandName
      text:
        ja: パーティコマンド名
      type: string
      default: 手引書
  commands: []
  structures:
    Guide:
      - param: title
        text:
          ja: 名前
        desc:
          ja: 手引書の目次に表示される名前を設定します。
        type: string
      - param: texts
        text:
          ja: 内容
        desc:
          ja: 手引書の具体的な内容を設定します。
        type: multiline_string[]
      - param: condition
        text:
          ja: 表示条件
        desc:
          ja: この条件を満たした場合にのみ手引書に表示します。
        type: Condition
        default:
          switchId: 0
          variableId: 0
          threshold: 0
    Condition:
      - param: switchId
        text:
          ja: スイッチ
        desc:
          ja: 指定した場合、このスイッチがONの場合のみ手引書に表示します。
        type: switch
        default: 0
      - param: variableId
        text:
          ja: 変数
        desc:
          ja: 指定した場合、この変数が閾値より大の場合のみ手引書に表示します。
        type: variable
        default: 0
      - param: threshold
        text:
          ja: 閾値
        type: number
        default: 0
  dependencies:
    base:
      - name: DarkPlasma_CustomKeyHandler
        version: 1.1.0
      - name: DarkPlasma_ManualText
        version: 1.3.0
    orderAfter:
      - name: DarkPlasma_CustomKeyHandler
      - name: DarkPlasma_ManualText
    orderBefore: []
  help:
    ja: |
      戦闘中に手引書を表示することができます。
