DarkPlasma_TextLog:
  name: DarkPlasma_TextLog
  year: 2022
  license: MIT
  histories:
    - date: 2023/12/23
      version: 2.1.1
      description: 'ゲーム開始直後にテキストを持たないイベントを実行すると自動区切り線が挿入される不具合を修正'
    - version: 2.1.0
      description: '自動区切り線の挿入を区切り線の直後に行わないように変更'
    - date: 2023/10/08
      version: 2.0.0
      description: '保持ログメッセージに関するプログラム上のインターフェース変更 (Breaking Change)'
    - description: '保持ログメッセージ件数設定を追加'
    - date: 2023/10/06
      version: 1.3.0
      description: 'ウィンドウ退避のインターフェースを公開'
    - date: 2023/09/21
      version: 1.2.1
      description: 'リファクタ'
    - date: 2023/07/22
      version: 1.2.0
      description: 'タッチUIが有効な場合にキャンセルボタンを表示'
    - version: 1.1.2
      description: '名前の制御文字をログ記録時点で展開するように修正'
    - date: 2023/01/30
      version: 1.1.1
      description: '決定キーでログウィンドウが閉じない不具合を修正'
    - date: 2022/11/03
      version: 1.1.0
      description: '開閉キーのpageup/pagedownを非推奨化'
    - description: '開閉キーでログウィンドウを閉じられない不具合を修正'
    - description: '決定キーでもログウィンドウを閉じられるように変更'
    - date: 2022/11/02
      version: 1.0.0
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: 'イベントテキストのログを保持・表示する'
  parameters:
    - param: disableLoggingSwitch
      text:
        ja: ログ記録無効スイッチ
      desc:
        ja: 設定したスイッチがONの間はログを残しません。0の場合、常にログを残します。
      type: switch
      default: 0
    - param: openLogKeys
      text:
        ja: ログ開閉ボタン
      desc:
        ja: テキストログウィンドウを開閉するためのボタンを設定します。
      type: select[]
      default: 
        - tab
      options:
        - name: shift
        - name: control
        - name: tab
        - name: pageup (非推奨)
          value: pageup
        - name: pagedown (非推奨)
          value: pagedown
    - param: disableLogWindowSwitch
      text:
        ja: ログウィンドウ無効スイッチ
      desc:
        ja: 設定したスイッチがONの間はログウィンドウを開けません。0の場合、常に開けます。
      type: switch
      default: 0
    - param: lineSpacing
      text:
        ja: ログの行間
      desc:
        ja: ログの行間を設定します。
      type: number
      default: 0
    - param: messageSpacing
      text:
        ja: メッセージ間隔
      desc:
        ja: ログのメッセージの間隔を設定します。メッセージはイベントコマンド単位でひとかたまりです。
      type: number
      default: 0
    - param: logSplitter
      text:
        ja: ログ区切り線
      desc:
        ja: イベントの切れ目などに挟むための区切り線を設定します。
      type: string
      default: '-------------------------------------------------------'
    - param: autoSplit
      text:
        ja: 自動区切り線
      desc:
        ja: ONの場合、バトル、コモン、並列イベントを除くイベント終了時に区切り線を自動で入れます。
      type: boolean
      default: true
    - param: choiceFormat
      text:
        ja: 選択肢フォーマット
      desc:
        ja: ログに表示する選択肢のフォーマットを設定します。{choice}は選んだ選択肢に変換されます。
      type: string
      default: 選択肢:{choice}
    - param: choiceColor
      text:
        ja: 選択肢色
      desc:
        ja: ログに表示する選択肢の色を設定します。
      type: number
      default: 17
    - param: choiceCancelText
      text:
        ja: キャンセルログ
      desc:
        ja: 選択肢をキャンセルした際に記録する内容を設定します。
      type: string
      default: キャンセル
    - param: smoothBackFromLog
      text:
        ja: テキスト再表示なし
      desc:
        ja: ONの場合、ログシーンから戻った際にテキストを再度表示し直しません。
      type: boolean
      default: true
    - param: backgroundImage
      text:
        ja: 背景画像
      desc:
        ja: ログシーンに表示する背景画像を設定します。
      type: file
      dir: img
    - param: showLogWindowFrame
      text:
        ja: ウィンドウ枠表示
      desc:
        ja: ONの場合、ログウィンドウ枠を表示します。
      type: boolean
      default: true
    - param: escapeCharacterCodes
      text:
        ja: パラメータを除外したい制御文字
      desc:
        ja: \XXX[YYY]の形式でYYYをログから消したい場合、ここにXXXを追加します。
      type: string[]
      default: []
    - param: scrollSpeed
      text:
        ja: スクロール速さ
      desc:
        ja: 上下キーによるスクロールの速さを設定します。大きいほど速くなります。
      type: number
      default: 1
      min: 1
    - param: scrollSpeedHigh
      text:
        ja: 高速スクロール速さ
      desc:
        ja: PageUp/PageDownキーによるスクロールの速さを設定します。
      type: number
      default: 10
      min: 1
    - param: maxLogMessages
      text:
        ja: ログメッセージ保持数
      desc:
        ja: ログメッセージを保持する件数を設定します。増やしすぎるとゲームの挙動に影響し得ることに注意してください。
      type: number
      default: 200
  commands:
    - command: showTextLog
      text:
        ja: ログウィンドウを開く
    - command: insertLogSplitter
      text:
        ja: ログに区切り線を追加する
    - command: insertTextLog
      text:
        ja: ログに指定したテキストを追加する
      args:
        - arg: text
          text:
            ja: テキスト
          type: string
  structures:
  dependencies:
    base: []
    orderAfter: []
    orderBefore: []
  help:
    ja: |
      イベントで表示されたテキストをログとして保持、表示します。
      ログはセーブデータには保持されません。

      マップ上、イベント中にログ開閉キーを押すことでログウィンドウを開きます。
      ログ開閉キー、決定キー、キャンセルキーのいずれかでログウィンドウを閉じます。
