DarkPlasma_ImportExportSaveFile:
  name: DarkPlasma_ImportExportSaveFile
  year: 2022
  license: MIT
  histories:
    - date: 2022/12/23
      version: 1.1.0
      description: 'インポート時の説明文をplaceholderに変更'
    - date: 2022/12/22
      version: 1.0.0
      description: 'リファクタ'
    - version: 0.0.1
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: 'セーブデータのインポート・エクスポート機能'
  parameters:
    - param: textAreaRect
      text:
        ja: セーブデータ表示エリア
      type: Rectangle
      default:
        x: 208
        y: 100
        width: 400
        height: 400
    - param: okButtonPos
      text:
        ja: OKボタン座標
      type: Point
      default:
        x: 308
        y: 520
    - param: cancelButtonPos
      text:
        ja: キャンセルボタン座標
      type: Point
      default:
        x: 508
        y: 520
    - param: menuButtonType
      text:
        ja: イン/エクスポートボタン位置
      type: select
      options:
        - name: 選択中のセーブファイル上
          value: 1
        - name: 指定した座標
          value: 2
      default: 1
    - param: importButtonPos
      text:
        ja: インポートボタン座標
      desc:
        ja: イン/エクスポートボタン位置設定が指定した座標である場合に有効です。
      type: Point
      default:
        x: 680
        y: 16
    - param: exportButtonPos
      text:
        ja: エクスポートボタン座標
      desc:
        ja: イン/エクスポートボタン位置設定が指定した座標である場合に有効です。
      type: Point
      default:
        x: 750
        y: 16
    - param: exportHelpText
      text:
        ja: エクスポート説明文
      type: string
      default: 表示されているテキストを保存してください。
    - param: importHelpText
      text:
        ja: インポート説明文
      type: string
      default: セーブデータのテキストを貼り付けてください。
    - param: buttonImages
      text:
        ja: ボタン画像
      type: ButtonImage
      default:
        ok: buttonOk
        cancel: buttonCancel
        import: buttonImport
        export: buttonExport
  commands: []
  structures:
    Rectangle:
      - param: x
        text:
          ja: X座標
        type: number
      - param: y
        text:
          ja: Y座標
        type: number
      - param: width
        text:
          ja: 横幅
        type: number
      - param: height
        text:
          ja: 高さ
        type: number
    Point:
      - param: x
        text:
          ja: X座標
        type: number
      - param: y
        text:
          ja: Y座標
        type: number
    ButtonImage:
      - param: ok
        text:
          ja: OKボタン
        type: file
        dir: img/system
        default: buttonOk
      - param: cancel
        text:
          ja: キャンセルボタン
        type: file
        dir: img/system
        default: buttonCancel
      - param: import
        text:
          ja: インポートボタン
        type: file
        dir: img/system
        default: buttonImport
      - param: export
        text:
          ja: エクスポートボタン
        type: file
        dir: img/system
        default: buttonExport
  dependencies:
    base: []
    orderAfter: []
    orderBefore: []
  help:
    ja: |
      本プラグインはkienさんの「セーブデータのインポート・エクスポート」を
      MZ移植したものです。

      このプラグインが動作するには以下の画像ファイルが
      img/system内に存在する必要があります：

      'buttonOk' :
      インポート・エクスポート画面においてユーザーの
      アクションを決定するボタンとして表示されます。
      'buttonCancel' : インポート画面において
      インポートを行わずにセーブ・ロード画面に戻るボタンとして表示されます。
      'buttonImport' : セーブ・ロード画面において
      インポート画面に移行するためのボタンとして表示されます。
      'buttonExport' : セーブ・ロード画面において
      エクスポート画面に移行するためのボタンとして表示されます。

      画像はデフォルト素材の'ButtonSet'と同様、
      上半分にデフォルト状態、
      下半分に押された状態の画像として作成してください。
