DarkPlasma_BuffRate:
  name: DarkPlasma_BuffRate
  year: 2020
  license: MIT
  histories:
    - date: 2023/09/23
      version: 2.1.0
      description: 'typescript移行'
    - description: '最大HP,最大MPに対応'
    - date: 2021/07/05
      version: 2.0.2
      description: 'MZ 1.3.2に対応'
    - date: 2021/06/22
      version: 2.0.1
      description: 'サブフォルダからの読み込みに対応'
    - date: 2020/09/08
      version: 2.0.0
      description: 'パラメータ名変更'
    - date: 2020/08/27
      version: 1.0.0
      description: 'MZ版公開'

  locates:
    - ja
  plugindesc:
    ja: '強化・弱体の倍率を個別に設定する'
  parameters:
    - param: maxHp
      text:
        ja: 最大HPの強化・弱体倍率
      type: BuffRate
      default:
        buffRate1: 25
        buffRate2: 50
        debuffRate1: 25
        debuffRate2: 50
    - param: maxMp
      text:
        ja: 最大MPの強化・弱体倍率
      type: BuffRate
      default:
        buffRate1: 25
        buffRate2: 50
        debuffRate1: 25
        debuffRate2: 50
    - param: attack
      text:
        ja: 攻撃力の強化・弱体倍率
      type: BuffRate
      default:
        buffRate1: 25
        buffRate2: 50
        debuffRate1: 25
        debuffRate2: 50
    - param: defense
      text:
        ja: 防御力の強化・弱体倍率
      type: BuffRate
      default:
        buffRate1: 25
        buffRate2: 50
        debuffRate1: 25
        debuffRate2: 50
    - param: magicAttack
      text:
        ja: 魔法力の強化・弱体倍率
      type: BuffRate
      default:
        buffRate1: 25
        buffRate2: 50
        debuffRate1: 25
        debuffRate2: 50
    - param: magicDefense
      text:
        ja: 魔法防御力の強化・弱体倍率
      type: BuffRate
      default:
        buffRate1: 25
        buffRate2: 50
        debuffRate1: 25
        debuffRate2: 50
    - param: agility
      text:
        ja: 敏捷性の強化・弱体倍率
      type: BuffRate
      default:
        buffRate1: 25
        buffRate2: 50
        debuffRate1: 25
        debuffRate2: 50
    - param: luck
      text:
        ja: 運の強化・弱体倍率
      type: BuffRate
      default:
        buffRate1: 25
        buffRate2: 50
        debuffRate1: 25
        debuffRate2: 50
  structures:
    BuffRate:
      - param: buffRate1
        text:
          ja: 1段階目強化倍率（％）
        type: number
        default: 25
      - param: buffRate2
        text:
          ja: 2段階目強化倍率（％）
        type: number
        default: 50
      - param: debuffRate1
        text:
          ja: 1段階目弱化倍率（％）
        type: number
        default: 25
      - param: debuffRate2
        text:
          ja: 2段階目弱化倍率（％）
        type: number
        default: 50
  help:
    ja: |
      能力強化・弱体の倍率を個別に設定できるようにします。
