DarkPlasma_FormationInBattle:
  name: DarkPlasma_FormationInBattle
  year: 2020
  license: MIT
  histories:
    - date: 2025/10/19
      version: 3.0.1
      description: 'TPB(ウェイト)で並び替えを開いても時間が止まらない不具合を修正'
    - date: 2024/10/17
      version: 3.0.0
      description: 'DarkPlasma_Formation 4.0.0対応'
    - date: 2024/03/07
      version: 2.1.2
      description: 'DarkPlasma_Formationとの順序関係を明記'
    - date: 2023/08/06
      version: 2.1.1
      description: '特定条件下でカーソルの合っていないアクターが選択されてしまう不具合を修正'
    - date: 2023/07/29
      version: 2.1.0
      description: 'DarkPlasma_Formation 2.1.0対応'
    - date: 2023/06/17
      version: 2.0.0
      description: 'DarkPlasma_Formation 2.0.0対応'
    - description: 'TypeScript移行'
    - date: 2022/08/02
      version: 1.2.7
      description: 'リファクタ'
    - version: 1.2.6
      description: 'リファクタ'
    - date: 2022/08/01
      version: 1.2.5
      description: 'DarkPlasma_Formation 1.3.2に対応'
    - date: 2022/03/31
      version: 1.2.4
      description: 'TemplateEvent.jsと併用すると戦闘テストできない不具合を修正'
    - date: 2021/07/05
      version: 1.2.3
      description: 'MZ 1.3.2に対応'
    - date: 2021/06/22
      version: 1.2.2
      description: 'サブフォルダからの読み込みに対応'
    - date: 2021/05/09
      version: 1.2.1
      description: '戦闘テスト開始時にエラーが発生する不具合を修正'
    - date: 2021/05/05
      version: 1.2.0
      description: '特定マップで戦闘中の並び替えを禁止する機能追加'
    - date: 2020/12/30
      version: 1.1.4
      description: 'DarkPlasma_Formation 1.2.0に対応'
    - date: 2020/12/16
      version: 1.1.3
      description: 'DarkPlasma_Formation 1.0.5に対応'
    - date: 2020/12/14
      version: 1.1.2
      description: '強制入れ替え時にエラーで落ちる不具合を修正'
    - date: 2020/10/19
      version: 1.1.1
      description: '戦闘開始時の不要な処理を削除'
    - date: 2020/10/13
      version: 1.1.0
      description: '強制入れ替え時のクールダウン設定を追加'
    - date: 2020/09/21
      version: 1.0.1
      description: '並び替え確定時にパーティウィンドウがリフレッシュされない不具合を修正'
    - date: 2020/09/13
      version: 1.0.0
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: '戦闘のパーティコマンドに並び替えを追加'
  parameters:
    - param: cooldownTurnCount
      text:
        ja: クールタイム
      desc:
        ja: 並び替え後、このターン数が経過するまで再度並び替えできない（0で即時変更可能）
      type: number
      default: 0
    - param: cooldownOnlyWhenSwapForwardAndBenchwarmer
      text:
        ja: 前後入れ替え時のみクール
      desc:
        ja: 前衛後衛を入れ替えた場合のみクールタイムを有効にする
      type: boolean
      default: true
    - param: cooldownFormat
      text:
        ja: クールタイム表示形式
      desc:
        ja: クールタイムの表示形式（{turn}がターン数に置き換えられる）
      type: string
      default: (CT:{turn})
    - param: cooldownWithForceFormation
      text:
        ja: 強制入れ替え時クールダウン
      desc:
        ja: 強制入れ替え時にもクールダウンする
      type: boolean
      default: true
  commands: []
  structures:
  dependencies:
    base:
      - name: DarkPlasma_Formation
        version: 4.0.0
    orderAfter:
      - name: DarkPlasma_Formation
  help:
    ja: |
      戦闘シーンで並び替えできるようになります。

      マップのメモ欄に<disableFormationInBattle>と記述することで、
      対象マップでの戦闘中に並び替えを選択できなくなります。
