DarkPlasma_DarkMap:
  name: DarkPlasma_DarkMap
  year: 2021
  license: MIT
  histories:
    - date: 2022/08/19
      version: 1.0.2
      description: 'typescript移行'
    - date: 2022/03/31
      version: 1.0.1
      description: 'TemplateEvent.jsと併用すると戦闘テストできない不具合を修正'
    - date: 2021/11/19
      version: 1.0.0
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: '暗いマップと明かり'
  parameters:
    - param: darkness
      text:
        ja: マップの暗さ
      desc:
        ja: 0～255の数値でマップの暗さを指定します。数字が大きくなるほど暗くなります。
      type: number
      default: 255
      max: 255
      min: 0
    - param: lightColor
      text:
        ja: 明かりの色
      type: Color
      default:
        red: 255
        green: 255
        blue: 255
    - param: lightRadius
      text:
        ja: 明かりの広さ
      type: number
      default: 200
  commands: []
  structures:
    Color:
      - param: red
        text:
          ja: 赤
        type: number
        default: 255
        max: 255
        min: 0
      - param: green
        text:
          ja: 緑
        type: number
        default: 255
        max: 255
        min: 0
      - param: blue
        text:
          ja: 青
        type: number
        default: 255
        max: 255
        min: 0
  dependencies:
    base: []
    orderAfter: []
    orderBefore: []
  help:
    ja: |
      暗いマップと、プレイヤーやイベントの周囲を照らす明かりを提供します。

      マップのメモ欄:
      <dark> 暗いマップにします。

      イベントのメモ欄:
      <light> イベントの周囲を照らします。
      <lightColor:#ffbb73> 明かりの色を設定します。
      <lightRadius:155> 明かりの範囲を設定します。
