DarkPlasma_SkillCostExtensionView:
  name: DarkPlasma_SkillCostExtensionView
  year: 2020
  license: MIT
  histories:
    - date: 2023/05/15
      version: 1.1.3
      description: 'プラグインパラメータの型を変更'
    - description: 'typescript移行'
    - date: 2021/07/05
      version: 1.1.2
      description: 'MZ 1.3.2に対応'
    - date: 2021/06/22
      version: 1.1.1
      description: 'サブフォルダからの読み込みに対応'
    - date: 2020/10/06
      version: 1.1.0
      description: '変数コストの色設定を追加'
    - date: 2020/10/04
      version: 1.0.1
      description: 'アイテムコストが正しく表示されない不具合を修正'
    - date: 2020/10/03
      version: 1.0.0
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: 'スキルコスト表示を拡張する'
  parameters:
    - param: hpCostColor
      text:
        ja: HPコスト色
      desc:
        ja: HPコストの色をツクールの色番号または#+6桁の16進数で指定します。
      type: color
      default: 2
    - param: itemCostColor
      text:
        ja: アイテムコスト色
      desc:
        ja: アイテムコストの色をツクールの色番号または#+6桁の16進数で指定します。
      type: color
      default: 0
    - param: goldCostColor
      text:
        ja: お金コスト色
      desc:
        ja: お金コストの色をツクールの色番号または#+6桁の16進数で指定します。
      type: color
      default: 6
    - param: variableCostColor
      text:
        ja: 変数コスト色
      desc:
        ja: 変数コストの色をツクールの色番号または#+6桁の16進数で指定します。
      type: color
      default: 5
  commands: []
  structures:
  dependencies:
    base:
      - name: DarkPlasma_SkillCostExtension
        version: 1.3.4
    orderAfter: []
    orderBefore:: []
  help:
    ja: |
      DarkPlasma_SkillCostExtensionで設定した拡張スキルコストを
      スキルリスト上で表示します。

      以下の優先度で対象スキルのコストを1つだけ表示します。
      変数 > お金 > アイテム > HP > TP > MP
