DarkPlasma_ChangePartyLeader:
  name: DarkPlasma_ChangePartyLeader
  year: 2022
  license: MIT
  histories:
    - date: 2022/11/06
      version: 1.0.0
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: 'パーティの先頭（リーダー）を変更する'
  parameters: []
  commands:
    - command: changeLeader
      text:
        ja: リーダーを変更する
      desc:
        ja: パーティリーダーを指定したアクターに変更します。（元のリーダーと隊列を入れ替えます）
      args:
        - arg: actorId
          text:
            ja: アクター
          type: actor
    - command: resetLeader
      text:
        ja: リーダーを元に戻す
      desc:
        ja: リーダーを変更プラグインコマンド実行直前の状態に戻します。
  structures:
  dependencies:
    base: []
    orderAfter: []
    orderBefore: []
  help:
    ja: |
      先頭のパーティメンバーを、現在パーティメンバーにいるアクターに
      入れ替えるプラグインコマンドを提供します。

      セーブデータに以下のデータを追加します。
      - プラグインコマンドでリーダーを変更する直前のリーダー

      尚、指定したアクターや元のリーダーがパーティメンバーにいない場合、
      プラグインコマンドは何もしません。
