DarkPlasma_HorizontalScrollWindow:
  name: DarkPlasma_HorizontalScrollWindow
  year: 2022
  license: MIT
  histories:
    - date: 2022/11/15
      version: 1.0.0
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: '横方向にスクロールするウィンドウ'
  parameters: []
  commands: []
  structures:
  dependencies:
    base: []
    orderAfter: []
    orderBefore: []
  help:
    ja: |
      本プラグインはプラグイン開発者向けです。

      以下のように記述することで、対象の選択ウィンドウの
      スクロール方向を縦から横に変更します。
      Window_HorizontalScrollMixIn(windowClass: Window_Selectable);
