DarkPlasma_ExpandTargetScopeButton:
  name: DarkPlasma_ExpandTargetScopeButton
  year: 2022
  license: MIT
  histories:
    - date: 2023/01/14
      version: 2.0.0
      description: 'typescript移行'
    - description: '全体化・単体化ボタンの設定が逆だったのを修正'
    - description: 'メニュー画面でのアイテム/スキル使用時にもボタンを表示する機能追加'
    - description: 'ボタンの座標設定を戦闘/メニューで分離'
    - date: 2022/01/07
      version: 1.0.1
      description: 'リファクタ'
    - date: 2022/01/03
      version: 1.0.0
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: 'スキル/アイテムの対象全体化切り替えボタン'
  parameters:
    - param: allButtonImage
      text:
        ja: 全体化ボタン画像
      desc:
        ja: 押すとスキル/アイテムの対象を全体化するボタンの画像を指定します。
      type: file
      dir: img
    - param: singleButtonImage
      text:
        ja: 単体化ボタン画像
      desc:
        ja: 押すとスキル/アイテムの対象を単体化するボタンの画像を指定します。
      type: file
      dir: img
    - param: positionInBattle
      text:
        ja: 戦闘画面上の座標
      type: Point
      default:
        x: 0
        y: 0
    - param: positionInMenu
      text:
        ja: メニュー画面上の座標
      type: PositionInMenu
      default:
        cursorLeft:
          x: 0
          y: 0
        cursorRight:
          x: 500
          y: 0
    - param: scale
      text:
        ja: サイズ倍率
      desc:
        ja: ボタン画像のサイズ倍率（％）
      type: number
      default: 100
  commands: []
  structures:
    PositionInMenu:
      - param: cursorLeft
        text:
          ja: カーソル左時の座標
        type: Point
        default:
          x: 0
          y: 0
      - param: cursorRight
        text:
          ja: カーソル右時の座標
        type: Point
        default:
          x: 500
          y: 0
    Point:
      - param: x
        text:
          ja: X座標
        type: number
        default: 0
      - param: y
        text:
          ja: Y座標
        type: number
        default: 0
  dependencies:
    base:
      - name: DarkPlasma_ExpandTargetScope
        version: 1.4.0
    orderAfter:
      - name: DarkPlasma_ExpandTargetScope
    orderBefore: []
  help:
    ja: |
      スキル/アイテムの対象を単体/全体に切り替えるボタンを表示します。
