DarkPlasma_UnusableItemWithMapEvent:
  name: DarkPlasma_UnusableItemWithMapEvent
  year: 2022
  license: MIT
  histories:
    - date: 2022/06/02
      version: 1.0.0
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: 'マップイベント実行中は使用できないアイテム'
  parameters: []
  commands: []
  structures:
  dependencies:
    base: []
    orderAfter: []
    orderBefore: []
  help:
    ja: |
      メモ欄に以下のように記述したアイテム・スキルは
      マップイベントの実行中には使用できなくなります。

      <unusableWithMapEvent>
