DarkPlasma_RandomTroop:
  name: DarkPlasma_RandomTroop
  year: 2023
  license: MIT
  histories:
    - date: 2023/08/21
      version: 1.0.0
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: '敵グループ構成のランダム化'
  parameters:
    - param: autoPositionWidth
      text:
        ja: 自動配置横幅
        en: auto position width
      desc:
        ja: 自動配置の際、前後に動かす際の横幅の閾値を設定します。敵キャラ画像の横幅合計がこれより大きい場合、敵配置を前後にバラけさせます。
        en: If sum of enemy image width is larger than this value, set enemy position front and back.
      type: number
      default: 816
    - param: enemyTypeTag
      text:
        ja: 敵種別タグ
      desc:
        ja: 敵種別を判定するためのメモタグ名を指定します。
      type: string
      default: enemyType
  commands:
    - command: randomTroop
      text:
        ja: ランダム構成設定
      desc:
        ja: 敵グループバトルイベントの1ページ目で使用すると、遭遇時にグループ構成をランダムに決定します。
      args:
        - arg: troop
          text:
            ja: 抽選枠設定
          desc:
            ja: 任意の数の抽選枠を設定します。
          type: RandomTroopEnemy[]
  structures:
    RandomTroopEnemy:
      - param: name
        text:
          ja: 抽選枠名(省略可)
        desc:
          ja: 抽選枠の名前を指定します。挙動には影響しません。管理しやすい名前をつけてください。
        type: string
        default: ""
      - param: enemyIds
        text:
          ja: 敵キャラリスト
        desc:
          ja: 抽選枠に指定した敵キャラを追加します。
        type: enemy[]
        default: []
      - param: tag
        text:
          ja: 敵種別
        desc:
          ja: 抽選枠に指定した敵種別メモタグを記述した敵キャラを追加します。
        type: string
        default: ""
      - param: rate
        text:
          ja: 抽選確率（％）
        desc:
          ja: この抽選枠が出現する確率を指定します。
        min: 0
        max: 100
        type: number
        default: 100
  dependencies:
    base: []
    orderAfter: []
    orderBefore: []
  help:
    ja: |
      敵グループのバトルイベント設定
      1ページ目でプラグインコマンドを設定することにより、
      設定内容に応じて遭遇時に敵グループの構成をランダムに決定します。

      抽選枠を任意の数指定することができ、指定した数だけ出現判定を行います。
      ある抽選枠が出現する判定となった場合、
      その抽選枠に含まれる敵キャラリストの中から
      ランダムで1体の敵キャラが出現します。

      敵種別を敵キャラのメモ欄で指定し、
      その種別を抽選枠に追加することも可能です。
      敵種別のメモタグはデフォルト設定では enemyType となっています。

      例:
      <enemyType:スライム族LV1>

      種別はカンマ区切りで複数指定することも可能です。
      <enemyType:スライム族LV1,スライム族LV2>
