DarkPlasma_EnemyLevel:
  name: DarkPlasma_EnemyLevel
  year: 2023
  license: MIT
  histories:
    - date: 2023/09/16
      version: 1.0.0
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: '敵キャラにレベルを設定する'
  parameters:
    - param: defaultLevel
      text:
        ja: デフォルトレベル
      type: number
      default: 1
  commands: []
  structures:
  dependencies:
    base: []
    orderAfter: []
    orderBefore: []
  help:
    ja: |
      敵キャラにレベルを設定できるようになります。

      敵キャラのメモ欄に以下のように記述すると、
      その敵キャラのレベルは1になります。
      <level:1>
      
      スキルのダメージ計算などに b.level と書けば、
      対象のレベルに応じた計算式を作ることができます。
