DarkPlasma_HighlightNewItem:
  name: DarkPlasma_HighlightNewItem
  year: 2021
  license: MIT
  histories:
    - date: 2022/08/23
      version: 1.1.1
      description: 'OrderEquipとの順序関係を明示'
    - date: 2022/08/21
      version: 1.1.0
      description: '新規入手アイテムを最上部に表示する設定を追加'
    - version: 1.0.6
      description: 'typescript移行'
    - date: 2021/09/19
      version: 1.0.5
      description: '同じIDの別種別のアイテムが新しく入手した扱いになる不具合を修正'
    - date: 2021/09/11
      version: 1.0.4
      description: '特定のクラスを操作するプラグインとの競合を修正'
    - date: 2021/09/06
      version: 1.0.3
      description: '外した装備が新しく入手した扱いになる不具合を修正'
    - date: 2021/09/06
      version: 1.0.2
      description: '装備のつけ外しでエラーになる不具合を修正'
    - date: 2021/09/05
      version: 1.0.1
      description: '売却時に入手した扱いになってしまう不具合を修正'
    - date: 2021/09/05
      version: 1.0.0
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: '新しく入手したアイテムをメニューのアイテム一覧で強調表示する'
  parameters:
    - param: newItemColor
      text:
        ja: アイテム色
      desc:
        ja: 新しく入手したアイテムの色番号を指定します。
      type: number
      default: 2
    - param: newItemToTop
      text:
        ja: 新規アイテムを最上部に
      desc:
        ja: ONの場合、新しく入手したアイテムを最上部に表示します。
      type: boolean
      default: false
  commands: []
  structures:
  dependencies:
    base: []
    orderAfter:
      - name: DarkPlasma_OrderIdAlias
      - name: DarkPlasma_OrderEquip
    orderBefore: []
  help:
    ja: |
      メニューのアイテム一覧で、新しく入手したアイテムを強調表示します。

      強調表示は一度カーソルを合わせると元の色に戻ります。
