DarkPlasma_ItemDetail:
  name: DarkPlasma_ItemDetail
  year: 2023
  license: MIT
  histories:
    - date: 2024/04/20
      version: 1.0.5
      description: '共通化した実装を基底プラグインに分離'
    - date: 2024/04/17
      version: 1.0.4
      description: '詳細説明を開けるウィンドウの実装を共通ファイルに切り出す'
    - version: 1.0.3
      description: '詳細説明ウィンドウの実装を共通ファイルに切り出す'
    - date: 2023/10/20
      version: 1.0.2
      description: '型の指定を修正 (動作に影響なし)'
    - version: 1.0.1
      description: '詳細ウィンドウの表示位置がズレる不具合を修正'
    - version: 1.0.0
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: 'アイテムの詳細説明文を表示する'
  parameters:
    - param: openDetailKey
      text:
        ja: 詳細説明ボタン
      desc:
        ja: 詳細説明を開くためのボタン
      type: select
      options:
        - name: pageup
        - name: pagedown
        - name: shift
        - name: control
        - name: tab
      default: shift
    - param: heightAdjustment
      text:
        ja: 詳細高さ補正
      desc:
        ja: 詳細ウィンドウコンテンツの高さ補正。
      type: number
      default: 32
  commands: []
  structures:
  dependencies:
    base:
      - name: DarkPlasma_CustomKeyHandler
        version: 1.3.0
      - name: DarkPlasma_DisplayDatabaseDetailWindow
        version: 1.0.0
    orderAfter:
      - name: DarkPlasma_CustomKeyHandler
      - name: DarkPlasma_DisplayDatabaseDetailWindow
    orderBefore: []
  help:
    ja: |
      アイテム画面のアイテムにカーソルを合わせて特定のボタンを押すと
      アイテム詳細説明画面を開きます。

      アイテムのメモ欄に下記のような記述で詳細説明を記述できます。
      <detail:詳細説明文。
      ～～～～。>
