DarkPlasma_SurpriseControlWithEventBattle:
  name: DarkPlasma_SurpriseControlWithEventBattle
  year: 2023
  license: MIT
  histories:
    - date: 2023/05/06
      version: 1.0.0
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: 'イベントコマンド「戦闘の処理」で先制攻撃/不意打ちの判定を行う'
  parameters: []
  commands: []
  structures:
  dependencies:
    base: []
    orderAfter: []
    orderBefore: []
  help:
    ja: |
      イベントコマンド「戦闘の処理」でも先制攻撃/不意打ちの判定を行います。
