DarkPlasma_PartitionTileLayer:
  name: DarkPlasma_PartitionTileLayer
  year: 2024
  license: MIT
  histories:
    - date: 2024/01/05
      version: 1.0.0
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: 'カーテンや衝立のようなタイルレイヤー'
  parameters:
    - param: terrainTag
      text:
        ja: 地形タグ
      desc:
        ja: カーテンや衝立を表す地形タグを設定します。
      type: number
      default: 1
  commands: []
  structures:
  dependencies:
    base: []
    orderAfter: []
    orderBefore: []
  help:
    ja: |
      マップにおいて、キャラクターが下のマスにいる場合は奥に、そのマスにいる場合は手前に
      表示されるような特殊なレイヤーに配置するタイルを設定します。
      ただし、そのようなタイルを上下に連続して配置した場合の仕様は定義しません。

      FSMのベッドのベッドボードの通行設定について
      下方向のみ通行不可にして侵入可能としてしまうと
      ベッドボードよりもキャラクターが手前に表示されてしまう問題を解決します。
