DarkPlasma_SkillWithTraits:
  name: DarkPlasma_SkillWithTraits
  year: 2023
  license: MIT
  histories:
    - date: 2023/10/14
      version: 1.0.0
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: '特徴付きスキル'
  parameters: []
  commands: []
  structures:
  dependencies:
    base: []
    orderAfter: []
    orderBefore: []
  help:
    ja: |
      習得しているだけで特徴が得られるスキルを実現します。
      特徴によって追加されたスキルには効果がありません。

      スキルのメモ欄に以下のように記述してください。
      <traits:actor/1>
      アクターID1と同じ特徴を得ます。

      <traits:class/1>
      職業ID1と同じ特徴を得ます。

      <traits:weapon/1>
      武器ID1と同じ特徴を得ます。

      <traits:armor/1>
      防具ID1と同じ特徴を得ます。

      <traits:state/1>
      ステートID1と同じ特徴を得ます。
