DarkPlasma_SetColorByCode:
  name: DarkPlasma_SetColorByCode
  year: 2023
  license: MIT
  histories:
    - date: 2023/06/29
      version: 1.0.1
      description: '色変更以外の制御文字を握り潰してしまう不具合を修正'
    - date: 2023/06/02
      version: 1.0.0
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: '制御文字による色指定を#から始まるカラーコードで行う'
  parameters: []
  commands: []
  structures:
  dependencies:
    base: []
    orderAfter: []
    orderBefore: []
  help:
    ja: |
      制御文字\Cによる色指定を、#から始まるカラーコードで行えるようにします。

      例: \C[#adff2f]
      黄緑色になります。
