DarkPlasma_ManualText:
  name: DarkPlasma_ManualText
  year: 2022
  license: MIT
  histories:
    - date: 2022/11/13
      version: 1.5.4
      description: 'refreshメソッドを無駄に上書きしないように修正'
    - date: 2022/09/11
      version: 1.5.3
      description: '正しく表示されない不具合を修正'
    - date: 2022/09/10
      version: 1.5.2
      description: '複数列表示時、正しく表示されない不具合を修正'
    - version: 1.5.1
      description: '複数列表示時、表示数が奇数の場合に正しく表示されない不具合を修正'
    - version: 1.5.0
      description: 'マニュアルの複数列表示に対応'
    - date: 2022/08/27
      version: 1.4.1
      description: 'typescript移行'
    - date: 2022/07/02
      version: 1.4.0
      description: 'マニュアルの行間設定を追加'
    - date: 2022/04/24
      version: 1.3.0
      description: '公開'
    - date: 2022/03/14
      version: 1.2.0
      description: 'マニュアル設定ごとにrefreshしないように修正'
    - description: '行間変更に対応'
    - date: 2021/11/20
      version: 1.1.0
      description: 'フォントサイズ変更に対応'
    - date: 2021/10/24
      version: 1.0.0
      description: '初版'

  locates:
    - ja
  plugindesc:
    ja: 'ウィンドウに操作説明を表示する'
  parameters:
    - param: linePadding
      text:
        ja: 行間
      desc:
        ja: マニュアルの行間を指定します。
      type: number
      default: 12
  commands: []
  structures:
  dependencies:
    base: []
    orderAfter: []
    orderBefore: []
  help:
    ja: |
      ウィンドウ右下に操作説明を表示できるようにします。

      本プラグインは単体では機能しません。
      本プラグインを必要とする別のプラグインと一緒に利用してください。

      開発者向け説明
      Window_ManualTextMixIn をウィンドウクラスに適用し、
      drawManual メソッドを適当な場所で呼び出してください。

      drawManual: () => void
      操作説明テキストを描画します。

      manualX: (index: number) => number
      操作説明テキストのX座標を返します。

      manualY: (index: number) => number
      操作説明テキストのY座標を返します。

      setManualOffsetY: (offset: number) => void
      操作説明テキストのY座標オフセットを設定します。

      manualOffsetY: () => void
      操作説明テキストのY座標オフセットを返します。

      manualLineHeight: () => number
      操作説明テキストの行の高さを返します。

      setManualPadding: (padding: number) => void
      操作説明テキストの行間を設定します。

      manualPadding: () => number
      操作説明テキストの行間を返します。

      initManualTexts: () => void
      操作説明テキストを初期化します。

      addManualText: (text: string) => void
      操作説明テキストを追加します。

      manualTexts: () => string[]
      操作説明テキスト一覧を返します。

      setManualFontSize: (size: number) => void
      操作説明テキストのフォントサイズを設定します。

      manualFontSize: () => number
      操作説明テキストのフォントサイズを返します。
      デフォルトは21

      isManualVisible: () => boolean
      操作説明テキストの可視状態を返します。

      setIsManualVisible: (isVisible: boolean) => void
      操作説明テキストの可視状態を変更します。

      setManualCols(cols: number) => void
      操作説明テキストの表示列数を設定します。

      setManualWidth(width: number) => void
      操作説明テキストの表示幅を設定します。
