DarkPlasma_Scene_MessageMixIn:
  name: DarkPlasma_Scene_MessageMixIn
  year: 2023
  license: MIT
  histories:
    - date: 2025/02/23
      version: 1.0.3
      description: 'ショップシーンに表示するとお金ウィンドウが複製されて位置がズレる不具合を修正'
    - date: 2023/09/21
      version: 1.0.2
      description: 'TextLogと併用するとログウィンドウを閉じることができない不具合を修正'
    - date: 2023/01/18
      version: 1.0.1
      description: 'すでにお金ウィンドウがあるシーンにはお金ウィンドウを再定義しない'
    - description: '指定シーンを開こうとするとエラーが起きる不具合を修正'
    - date: 2023/01/13
      version: 1.0.0
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: '指定のシーンにメッセージウィンドウを表示させる'
  parameters:
    - param: scenes
      text:
        ja: シーン
      type: string[]
      default: []
  commands: []
  structures:
  dependencies:
    base: []
    orderAfter: []
    orderBefore: []
  help:
    ja: |
      パラメータで指定したシーンにメッセージウィンドウを表示できるようになります。

      $gameMessage.add などでメッセージを追加した際に、
      そのシーンでもメッセージを表示します。
