DarkPlasma_Scene_MessageMixIn:
  name: DarkPlasma_Scene_MessageMixIn
  year: 2023
  license: MIT
  histories:
    - date: 2023/01/13
      version: 1.0.0
      description: '公開'

  locates:
    - ja
  plugindesc:
    ja: '指定のシーンにメッセージウィンドウを表示させる'
  parameters:
    - param: scenes
      text:
        ja: シーン
      type: string[]
      default: []
  commands: []
  structures:
  dependencies:
    base: []
    orderAfter: []
    orderBefore: []
  help:
    ja: |
      パラメータで指定したシーンにメッセージウィンドウを表示できるようになります。

      $gameMessage.add などでメッセージを追加した際に、
      そのシーンでもメッセージを表示します。
